name: CI
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  tests-and-coverage:
    uses: mitlibraries/.github/.github/workflows/ruby-shared-ci.yml@main
