name: CI
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  mitlibraries-ruby-ci:
    uses: mitlibraries/actions-workflows/workflows/ruby-ci.yml@main
