# This workflow runs Lambda container deployments dev ONLY
name: Dev Lambda Container Deploy

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      GHA_ROLE:
        required: true
        type: string
      ECR:
        required: true
        type: string
      FUNCTION:
        required: true
        type: string

# Set defaults
defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy build
    runs-on: ubuntu-latest
    # This line adds a check for the user which is requesting the PR. As long as its not dependabot, we go ahead and run it. 
    if: ${{ github.triggering_actor != 'dependabot[bot]' }}
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCT_DEV }}:role/${{ inputs.GHA_ROLE }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Create tags
        id: tags
        run: |
          if [ $GITHUB_EVENT_NAME = "workflow_dispatch" ]; then
            TAG_SHA=$(echo $GITHUB_SHA | cut -c 1-8)
          else
            TAG_SHA=$(echo ${{ github.event.pull_request.head.sha }} | cut -c 1-8)
          fi
          if [ $GITHUB_EVENT_NAME = "workflow_dispatch" ]; then
            TAG_PR=$GITHUB_EVENT_NAME
          else
            TAG_PR=$(echo "PR-"${{ github.event.pull_request.number }})
          fi
          echo "::set-output name=tag_sha::$TAG_SHA"
          echo "::set-output name=tag_pr::$TAG_PR"

      - name: Build container
        run: |
          TAG_SHA="${{ steps.tags.outputs.tag_sha }}"
          TAG_PR="${{ steps.tags.outputs.tag_pr }}"
          DOCKER_BUILDKIT=1 docker build --platform linux/amd64 -t ${{ secrets.AWS_ACCT_DEV }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com/${{ inputs.ECR }}:latest -t ${{ secrets.AWS_ACCT_DEV }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com/${{ inputs.ECR }}:`echo $TAG_SHA` -t ${{ secrets.AWS_ACCT_DEV }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com/${{ inputs.ECR }}:`echo $TAG_PR` .

      - name: Push container
        run: |
          TAG_SHA="${{ steps.tags.outputs.tag_sha }}"
          TAG_PR="${{ steps.tags.outputs.tag_pr }}"
          docker login -u AWS -p $(aws ecr get-login-password --region ${{ inputs.AWS_REGION }}) ${{ secrets.AWS_ACCT_DEV }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com
          docker push ${{ secrets.AWS_ACCT_DEV }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com/${{ inputs.ECR }}:latest
          docker push ${{ secrets.AWS_ACCT_DEV }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com/${{ inputs.ECR }}:`echo $TAG_SHA`
          docker push ${{ secrets.AWS_ACCT_DEV }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com/${{ inputs.ECR }}:`echo $TAG_PR`
 
      - name: Update Lambda Function
        run: aws lambda update-function-code --function-name ${{ inputs.FUNCTION }} --image-uri ${{ secrets.AWS_ACCT_DEV }}.dkr.ecr.${{ inputs.AWS_REGION }}.amazonaws.com/${{ inputs.ECR }}:latest --query "LastUpdateStatusReasonCode" --output text
