# This workflow runs linters on the repo.
# Requirements: Calling repo must contain a .python-version file and  a Makefile with a
# `make lint` command.
name: Python Shared Linting Workflow

on:
  workflow_call:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get python version
        run: |
          python_version=$(cat .python-version)
          echo "python_version=${python_version}" >> $GITHUB_ENV

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
          architecture: x64

      - name: Install
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev

      - name: Lint
        run: make lint
