name: Ruby Shared CI

on:
  workflow_call:

jobs:
  test:
    name: Run Tests and Coverage
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: bundle-use-ruby-ubuntu-22.04-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-ubuntu-22.04-${{ hashFiles('.ruby-version') }}-
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: run tests
        run: |
          bundle exec rails test
      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov/coverage.lcov
