name: Validate Terraform

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  validate-terraform:
    name: terraform fmt & validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
      
      - name: Check format and validate
        run:
          terraform fmt -check -recursive; terraform init -backend=false; terraform validate
